services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - APIFY_API_TOKEN=${APIFY_API_TOKEN}
    restart: unless-stopped
