name: Daily MongoDB to S3 Backup

on:
  schedule:
    - cron: '50 20 * * *'
  workflow_dispatch:

jobs:
  backup-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Backup using mongodump (Docker)
        run: |
          echo "Starting MongoDB backup..."
          # הורדנו את חיבור התיקיות הבעייתי, ואנחנו שומרים את הפלט ישירות לקובץ על השרת
          docker run --rm mongo:latest mongodump --uri="${{ secrets.MONGO_URI }}" --archive --gzip > my_project_backup_$(date +%Y%m%d).gz

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload Backup to S3
        run: |
          echo "Uploading backup to S3 bucket..."
          aws s3 cp my_project_backup_*.gz s3://${{ secrets.AWS_S3_BUCKET }}/backups/
          echo "Backup uploaded successfully!"